linkWorkspacePackages: true
engineStrict: true
neverBuiltDependencies: []

overrides:
  "@effect/cluster": "npm:@effect/cluster@0.55.0"
  "@effect/rpc": "npm:@effect/rpc@0.72.2"
  "@effect/sql": "npm:@effect/sql@0.48.6"
  "@expo/metro-runtime": "npm:@expo/metro-runtime@6.1.2"
  vite: "npm:vite@7.2.7"
  srvx: "npm:srvx@0.9.8"
  lightningcss: "npm:lightningcss@1.30.1"
  react: "npm:react@19.1.4"
  react-dom: "npm:react-dom@19.1.4"

packages:
  - "docs"
  - "examples/*"
  - "examples/backend-adapters/*"
  - "packages/*"
  - "packages/nuxt/playground"
  - "!packages/raycast-extension"
  - "playground"
  - "playground-v6"
  - "tooling/*"
