preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
neverBuiltDependencies: []

overrides:
  vite: 7.2.7
  srvx: 0.9.8
  lightningcss: 1.30.1

packages:
  - "docs"
  - "examples/*"
  - "examples/backend-adapters/*"
  - "packages/*"
  - "packages/nuxt/playground"
  - "!packages/raycast-extension"
  - "playground"
  - "playground-v6"
  - "tooling/*"
