preferWorkspacePackages: true
saveWorkspaceProtocol: false
linkWorkspacePackages: true
engineStrict: true
neverBuiltDependencies: []

packages:
  - "docs"
  - "examples/*"
  - "examples/backend-adapters/*"
  - "packages/*"
  - "packages/nuxt/playground"
  - "!packages/raycast-extension"
  - "playground"
  - "playground-v6"
  - "tooling/*"

overrides:
  rolldown@*: rolldown@1.0.0-beta.32
