packages:
  - "docs"
  - "examples/*"
  - "examples/backend-adapters/*"
  - "packages/*"
  - "packages/nuxt/playground"
  - "!packages/raycast-extension"
  - "playground"
  - "playground-v6"
  - "tooling/*"
